---
title: "Questionable Reform"
subtitle: "Unit 3"
---

## **Overview** 
I am trying to reach a larger audience and bring attention to a few important events that happened in the United States history. During the early and mid 1800s there were many instances of questionable reform, from Second Bank of America, the Force Bill of 1833, and the Indian Removal Act in 1830. If you want to learn more, I talk about this in my essay below! 

## **Essay** 


Andrew Jackson bad
Questionable Reform
Throughout the United States history there have been many cases of questionable reform. The reform only slightly helped solve the overall problem or it was done deceptively to further an ulterior motive. Between 1829 - 1837 many of these half-Smeasured reforms were created and used by Andrew Jackson, the president at the time. Andrew Jackson’s conflict with the Second Bank of America, the Force Bill of 1833, and the Indian Removal Act in 1830 are all excellent examples of questionable reform.



Throughout the years of Andrew Jackson’s presidency, he heavily fought against the Second Bank of the United States as he claimed it was corrupt due to foreign and wealthy influence. After the Panic of 1819, Jackson was distrustful of the Federal Banks. When he became president, Jackson fought against the recharter of the Second Bank of the United States, he believed, “The Bank was also dangerous to liberty, because its concentrated power gave it a “fearful influence” over citizens' lives and an unchecked sway over government, inviting corruption and oppression.”[^1] Jackson was afraid that the rich and powerful as well as foreign shareholders would cause the Bank of the United States to stop caring about the “farmers, mechanics, and laborers”[^2] who also invested in the bank. He strongly maintained that “If we must have a bank,” Jackson warned, “it should be purely American.”[^3] He went on to veto the recharter after it was passed by both the Senate and House of Representatives. After Jackson was reelected as president, he took the federal deposits out of the Second Bank of the United States forcing Nicholas Biddle, a president of the Second Bank of the United States, to reduce the loans the bank was giving businesses. This created a lot of distress for both businesses and the economy, “his action instead discredited the Bank by reinforcing Jackson's warnings of its irresponsible power.”[^4] This created a large amount of distrust in the banking system from the working class and business owners as it proved that Jackson was correct, the bank had too much power over the economy. Andrew Jackson put the federal deposits that he withdrew from the Second Bank of the United States into state banks who went on large loaning sprees. After Jackson’s presidency ended most of the state banks collapsed since they loaded out too much of their money which led to a depression. This proves that Jackson’s reform of the Second Bank of the United States didn’t actually help the economy or especially the state banks. Jackson fought against federal banking only to have the entire economy collapse as state banks couldn’t manage the large amounts of money that was deposited into them. 

[^1]:  Feller, Daniel. 2008. “King Andrew and the Bank | The National Endowment for the Humanities.” The National Endowment For The Humanities. https://www.neh.gov/humanities/2008/januaryfebruary/feature/king-andrew-and-the-bank.
[^2]:  Feller, Daniel. 2008. “King Andrew and the Bank | The National Endowment for the Humanities.” The National Endowment For The Humanities. https://www.neh.gov/humanities/2008/januaryfebruary/feature/king-andrew-and-the-bank.
[^3]:  Feller, Daniel. 2008. “King Andrew and the Bank | The National Endowment for the Humanities.” The National Endowment For The Humanities. https://www.neh.gov/humanities/2008/januaryfebruary/feature/king-andrew-and-the-bank.
[^4]:  Feller, Daniel. 2008. “King Andrew and the Bank | The National Endowment for the Humanities.” The National Endowment For The Humanities. https://www.neh.gov/humanities/2008/januaryfebruary/feature/king-andrew-and-the-bank. 

In 1829 Andrew Jackson was appointed president of the United States, in his inauguration speech Jackson made a point to talk about how much he supported state rights and wanted “equal in sovereignty, and in claims to the benefits accruing from the confederation,” for the states. He continued to say that, “The operation of the principle, as fixed on this equitable basis, will give to the states the fiscal prosperity of the nation, and secure harmony by removing the grounds of Jealousy.”[^5] This is ironic because only a few years later Congress passed, and Andrew Jackson signed into law, the Force Bill of 1833 which gave the president, Andrew Jackson, the power to send military forces to states who were refusing to pay the tariff on imported goods. The Tariff of 1828, or the Tariff of Abomination as John C. Calhoun called it, taxed imported goods into the United States. The Southern States were especially at a disadvantage since they heavily relied on importation. John C. Calhoun said, “[The Tariff Law] of which the principal object is the protection of manufactures, or any other branch of domestic industry, if they be considered as the exercise of a supposed power in Congress to tax the people at its own good will and pleasure, and to apply the money raised to objects not specified in the Constitution, is a violation of these fundamental principles, a breach of a well defined trust and a perversion of the high powers vested in the Federal Government for federal purposes only.”[^6] This quote exemplifies the anger that many people in the southern states who relied on imported goods felt about the Tariff of 1833. Since Andrew Jackson said in his inaugural address that “all the states are equal in sovereignty, and in claims to the benefits accruing from the confederation”[^7], yet many southern states felt that they were not equal to the northern states as they had to pay extremely high tariffs on imported goods.  Andrew Jackson said in his Nullification Proclamation that, “two acts for the same purposes, passed on the 29th of May, 1828, and on the 14th of July, 1832, are unauthorized by the Constitution of the United States, and violate the true meaning and intent thereof, and are null and void, and no law"[^8]. After proclaiming that the acts are unconstitutional and therefore null and void Congress passed the Force Bill. The southern states felt threatened by the threat of military force used against them. Andrew Jackson’s Nullification Proclamation is an example of questionable reform as it was almost immediately followed by the Force Bill which contrasted what he said a year earlier. Andrew Jackson quickly changed his mind and might have only said he was in support of state rights to gain the approval of the states and people in southern states. 

[^5]: Jackson, Andrew. 1829. “Jackson's First Inauguration - American Treasures of the Library of Congress | Exhibitions.” Library of Congress. https://www.loc.gov/exhibits/treasures/trr075a.html. 
[^6]:  Calhoun, John C. 1828. “Exposition and Protest, Reported by the Special Committee of the House of Representatives, on The Tariff.” HOUSE_CR_Exposition_and_Protest. https://dc.statelibrary.sc.gov/bitstream/handle/10827/21911/HOUSE_CR_Exposition_and_Protest_1828-12-19.pdf?sequence=1&isAllowed=y. 
[^7]: Jackson, Andrew. 1829. “Jackson's First Inauguration - American Treasures of the Library of Congress | Exhibitions.” Library of Congress. https://www.loc.gov/exhibits/treasures/trr075a.html. 
[^8]:  Jackson, Andrew. 1832. “President Jackson's Proclamation Regarding Nullification, December 10, 1832(1).” In Lillian Goldman Law Library. Yale Law School: The Avalon Project. https://avalon.law.yale.edu/19th_century/jack01.asp. 


During Andrew Jackson’s two presidential terms he passed the Indian Removal Act in 1830 and heavily supported forcibly moving the Native Americans who lived on the eastern side of the country further west as both slavery and territory expanded. Andrew Jackson strongly believed that, “perhaps cause them gradually, under the protection of the Government and through the influence of good counsels, to cast off their savage habits and become an interesting, civilized, and Christian community”[^9]. Jackson fully believed that forcibly removing thousands of people from their homes could be a good thing as they could, effectively, assimilate into white American culture. He thought that reforming the United States relationships with the Native Americans located in the South meant allowing them to be seen as sovereign nations since the Federal government could then create treaties that would ultimately evict them from their homes. Other historians may argue that since none of Andrew Jackson’s reforms attempted to produce positive change the theme for reform does not connect to indigenous removal. On the contrary a court case, Worcester v. Georgia, stated that, “several treaties had been entered into by the United States with the Cherokee Nation by which that Nation was acknowledged to be a sovereign nation, and by which the territory occupied by them was guaranteed to them by the United States; and that the laws of Georgia under which the plaintiff in error was indicted are repugnant to the treaties”[^10]. This clearly shows that some Native American Nations did have rights as a sovereign nation in the eyes of the Federal government, even if it was only for a short while. The State of Georgia also couldn’t pass laws or treaties with the Native American tribes within the state as they were considered a sovereign nation. This granted them some rights and protections from the states. Overall, Andrew Jackson’s motivation to remove the Native Americans from their land wasn’t in their favor, but they were granted some rights as they were finally viewed as a sovereign nation.

[^9]:  “President Andrew Jackson's Message to Congress 'On Indian Removal' (1830).” 2022. National Archives |. https://www.archives.gov/milestone-documents/jacksons-message-to-congress-on-indian-removal.  
[^10]: U.S. Supreme Court. 1832. “Worcester v. Georgia, 31 U.S. 515 (1832).” JUSTIA U.S. Supreme Court. https://supreme.justia.com/cases/federal/us/31/515/.


Another example of questionable reform is the Fugitive Slave Act of 1793 and 1850. As James W. Loewen mentions in his book, Lies Across America, that the 1850 addition to the act was an extremely controversial reform. Many people, especially in the North, were outraged when kidnappings and the brutality towards escaped African Americans escalated[^11]. On the opposite side of this debate, the people in the South, particularly plantation and slave owners, supported the new Fugitive Slave Acts as they didn’t want to lose the people who were enslaved and working for them. This is considered questionable reform because it was a legal process that denied both escaped and free African Americans from being safe, even in free states. 

[^11]: Loewen, James W. 2019. Lies Across America: What Our Historic Sites Get Wrong. N.p.: New Press.


Clearly there are many different instances of questionable reform throughout American history, and specifically during Andrew Jackson’s presidency. The theme of questionable reform connects a variety of topics as it is something that permeates a considerable amount of our history and present day. People are always discussing and arguing over new laws and the way things are being run. While working on this project, I struggled to connect my three topics at first as well as finding the relationship between my theme and the themes in Lies Across America. Although I do think I achieved my goals that I set for myself at the beginning of the Unit. I definitely learned more about the context in which laws were passed and how the country was changing. After researching for and writing this essay, I feel like I can better understand the dates on which things happened and can better put it into context with other things that were happening at the same time. Overall, I have a better grasp on the process of the CEIs and feel decently prepared for the next units. Finally, the theme of questionable reform shows how many different topics are connected to each other by the discourse and discussions they create. It also brings out many new questions that can be talked about for years to come. 

